// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201213705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Currency"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Metals"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Crypto"
                        });
                });

            modelBuilder.Entity("backend.Models.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("API_LastUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Prices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 0.863m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 2,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 42.5054m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 3,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 77.73m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 4,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 41.98m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 5,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 1.1588m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 6,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 49.2618m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 7,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 89.88m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 8,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 48.68m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 9,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.02353m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 10,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.02029m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 11,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 1.825m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 12,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.9885m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 13,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.0129m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 14,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.01113m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 15,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.548m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 16,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.5417m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 17,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 0.02382m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 18,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 0.02054m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 19,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 1.012m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 20,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 11, 30, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 1.846m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 15, 31, 849, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 21,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 0.8625m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 43, 821, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 22,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 42.5085m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 119, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 23,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 77.6748m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 207, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 24,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "USD",
                            Rate = 42.2858m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 294, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 25,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 1.1594m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 377, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 26,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 49.2876m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 463, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 27,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 90.4284m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 545, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 28,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "EUR",
                            Rate = 48.9455m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 628, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 29,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.02352m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 715, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 30,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.02029m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 802, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 31,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 1.8244m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 887, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        },
                        new
                        {
                            Id = 32,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "TRY",
                            Rate = 0.9951m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 44, 979, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 33,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.01283m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 76, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 34,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.01111m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 172, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 35,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.5481m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 254, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 36,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "RUB",
                            Rate = 0.5423m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 343, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "UAH"
                        },
                        new
                        {
                            Id = 37,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 0.02365m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 427, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "USD"
                        },
                        new
                        {
                            Id = 38,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 0.02043m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 505, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "EUR"
                        },
                        new
                        {
                            Id = 39,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 1.0050m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 592, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "TRY"
                        },
                        new
                        {
                            Id = 40,
                            API_LastUpdatedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 0, 0, 1, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            BaseCurrency = "UAH",
                            Rate = 1.8440m,
                            SavedAtUtc = new DateTimeOffset(new DateTime(2025, 12, 1, 22, 52, 45, 680, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            TargetCurrency = "RUB"
                        });
                });

            modelBuilder.Entity("backend.Models.ScheduledTaskLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastRunUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScheduledTaskLogs");
                });

            modelBuilder.Entity("backend.Models.Subcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Category_id");

                    b.ToTable("Subcategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category_id = 1,
                            Code = "TL",
                            Name = "Turkish Lira"
                        },
                        new
                        {
                            Id = 2,
                            Category_id = 1,
                            Code = "EUR",
                            Name = "Euro"
                        },
                        new
                        {
                            Id = 3,
                            Category_id = 1,
                            Code = "USD",
                            Name = "US Dollar"
                        },
                        new
                        {
                            Id = 4,
                            Category_id = 1,
                            Code = "UAH",
                            Name = "Ukrainian Hryvnia"
                        },
                        new
                        {
                            Id = 5,
                            Category_id = 1,
                            Code = "RUB",
                            Name = "Russian Ruble"
                        },
                        new
                        {
                            Id = 6,
                            Category_id = 2,
                            Code = "AU",
                            Name = "Gold"
                        },
                        new
                        {
                            Id = 7,
                            Category_id = 2,
                            Code = "AG",
                            Name = "Silver"
                        },
                        new
                        {
                            Id = 8,
                            Category_id = 2,
                            Code = "PT",
                            Name = "Platinum"
                        },
                        new
                        {
                            Id = 9,
                            Category_id = 3,
                            Code = "BTC",
                            Name = "Bitcoin"
                        },
                        new
                        {
                            Id = 10,
                            Category_id = 3,
                            Code = "ETH",
                            Name = "Etherium"
                        },
                        new
                        {
                            Id = 11,
                            Category_id = 3,
                            Code = "XRP",
                            Name = "Ripple"
                        });
                });

            modelBuilder.Entity("backend.Models.Subcategory", b =>
                {
                    b.HasOne("backend.Models.Category", "Category")
                        .WithMany("Subcategories")
                        .HasForeignKey("Category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("backend.Models.Category", b =>
                {
                    b.Navigation("Subcategories");
                });
#pragma warning restore 612, 618
        }
    }
}
